In [73]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import datetime
df = pd.read_csv("2_isf2.csv",index_col=0)
df39 = df[df['cate_id']==39]
df39_date = df39.date.value_counts()
df39_date.sort_index()
df39_date = pd.DataFrame(df39_date)
df39_date.columns = ['num']
df39_date['date'] = df39_date.index
days_20141009 = datetime.datetime(2014, 10, 9)
df39_date['days_20141009'] = df39_date['date'].map(lambda x:(datetime.datetime(x/10000,x/100%100,x%100)-days_20141009).days)
plt.plot(df39_date.days_20141009,df39_date.num,'ro')
plt.show()

In [100]:
df['new_level'] = df['cate_id'].map(lambda x:str(x)+"*")
df['new_level2'] = df['cate_level_id'].map(lambda x:str(x)+"_")
df['new_level'] = df['new_level2'] + df['new_level']

In [53]:
x = df39_date.date.map(lambda x:str(x/10000)+"-"+str(x/100%100).zfill(2)+"-"+str(x%100).zfill(2))

In [72]:
from matplotlib import dates

In [ ]:
matplotlib.dates.DateFormatter('%y-%m-%d')
df39_date.plot(df39_date['days_20141009'],df39_date['num'])
#ax1.xaxis.set_major_formatter(mdates.DateFormatter("%Y-%m-%d"))
plt.show()

In [102]:
df['new_level'].value_counts().sort_index()

10_33*     15084
11_21*     73734
11_30*      9856
11_32*     79701
11_37*     61807
11_4*      37423
11_5*        894
12_11*     12367
12_15*      1057
12_17*     79774
12_18*     47195
12_25*      8976
12_28*       379
12_39*    116443
12_7*      45939
13_35*     67748
1_13*      84397
3_10*       1851
4_16*       1729
4_19*       2449
4_22*      31089
4_23*        753
4_36*       3874
4_9*        1573
5_20*      36644
6_24*        322
7_14*      19642
8_26*     107420
Name: new_level, dtype: int64

In [14]:
df39_date

,date,days_20141009
20151111,20151111,398 days
20151110,20151110,397 days
20150810,20150810,305 days
20151212,20151212,429 days
20150812,20150812,307 days
20150813,20150813,308 days
20150815,20150815,310 days
20150814,20150814,309 days
20150805,20150805,300 days
20150809,20150809,304 days
20150727,20150727,291 days
20150804,20150804,299 days
20150728,20150728,292 days
20150807,20150807,302 days
20150726,20150726,290 days
20150802,20150802,297 days
20150811,20150811,306 days
20150808,20150808,303 days
20150723,20150723,287 days
20150720,20150720,284 days
20150721,20150721,285 days
20150803,20150803,298 days
20150806,20150806,301 days
20150711,20150711,275 days
20150729,20150729,293 days
20150724,20150724,288 days
20150718,20150718,282 days
20150801,20150801,296 days
20150722,20150722,286 days
20150725,20150725,289 days
...,...,...
20150124,20150124,107 days
20150214,20150214,128 days
20150212,20150212,126 days
20141223,20141223,75 days
20141012,20141012,3 days
20141224,20141224,76 days
20141231,20141231,83 days
20141118,20141118,40 days
20141123,20141123,45 days
20141025,20141025,16 days
20150222,20150222,136 days
20141015,20141015,6 days
20141023,20141023,14 days
20141013,20141013,4 days
20141017,20141017,8 days
20141018,20141018,9 days
20141019,20141019,10 days
20141010,20141010,1 days
20141022,20141022,13 days
20141016,20141016,7 days
20150221,20150221,135 days
20141021,20141021,12 days
20150216,20150216,130 days
20150217,20150217,131 days
20141020,20141020,11 days
20141014,20141014,5 days
20150219,20150219,133 days
20141011,20141011,2 days
20150220,20150220,134 days
20150218,20150218,132 days

In [74]:
import numpy as np
from matplotlib import pyplot as plt
from matplotlib import dates
import datetime

a = np.array([
    [1293605162197, 0, 0],
    [1293605477994, 63, 0],
    [1293605478057, 0, 0],
    [1293605478072, 2735, 1249],
    [1293606162213, 0, 0],
    [1293606162229, 0, 0]])

d = a[:,0]
y1 = a[:,1]
y2 = a[:,2]

# convert epoch to matplotlib float format
s = d/1000
ms = d-1000*s  # not needed?
dts = map(datetime.datetime.fromtimestamp, s)
fds = dates.date2num(dts) # converted

# matplotlib date format object
hfmt = dates.DateFormatter('%m/%d %H:%M')

In [82]:
hfmt

In [ ]:
fig = plt.figure()
ax = fig.add_subplot(111)
ax.vlines(fds, y2, y1)

ax.xaxis.set_major_locator(dates.MinuteLocator())
ax.xaxis.set_major_formatter(hfmt)
ax.set_ylim(bottom = 0)
plt.xticks(rotation='vertical')
plt.subplots_adjust(bottom=.3)
plt.show()