In [27]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import datetime

    
def showCate_level_id(cate_level_ID,number):
    df = pd.read_csv("2_isf2.csv",index_col=0)
    df39 = df[df['cate_level_id']==cate_level_ID]
    df39_date = df39.date.value_counts()
    df39_date.sort_index()
    df39_date = pd.DataFrame(df39_date)
    df39_date.columns = ['num']
    df39_date['date'] = df39_date.index
    days_20141009 = datetime.datetime(2014, 10, 9)
    df39_date['days_20141009'] = df39_date['date'].map(lambda x:(datetime.datetime(x/10000,x/100%100,x%100)-days_20141009).days)
    plt.plot(df39_date.days_20141009,df39_date.num,'ro')
    #plt.show()
    plt.savefig('/Users/zhuohaizhen/Desktop/BigClass/'+str(number)+"-"+str(cate_level_ID)+".jpg")
    plt.show()
    plt.close('all')

In [30]:
showCate_level_id(12,1)
showCate_level_id(11,2)
showCate_level_id(8,3)
showCate_level_id(1,4)
showCate_level_id(13,5)
showCate_level_id(4,6)
showCate_level_id(5,7)
showCate_level_id(7,8)
showCate_level_id(10,9)
showCate_level_id(3,10)
showCate_level_id(6,11)

In [34]:
df = pd.read_csv("2_isf2.csv",index_col=0)

In [37]:
df39 = df[df['cate_id']==39]

In [43]:
df = pd.read_csv("2_isf2.csv",index_col=0)
for i,j in df.groupby([df['cate_level_id'],df['cate_id']]):
    print i
    print type(j)

(1, 13)
<class 'pandas.core.frame.DataFrame'>
(3, 10)
<class 'pandas.core.frame.DataFrame'>
(4, 9)
<class 'pandas.core.frame.DataFrame'>
(4, 16)
<class 'pandas.core.frame.DataFrame'>
(4, 19)
<class 'pandas.core.frame.DataFrame'>
(4, 22)
<class 'pandas.core.frame.DataFrame'>
(4, 23)
<class 'pandas.core.frame.DataFrame'>
(4, 36)
<class 'pandas.core.frame.DataFrame'>
(5, 20)
<class 'pandas.core.frame.DataFrame'>
(6, 24)
<class 'pandas.core.frame.DataFrame'>
(7, 14)
<class 'pandas.core.frame.DataFrame'>
(8, 26)
<class 'pandas.core.frame.DataFrame'>
(10, 33)
<class 'pandas.core.frame.DataFrame'>
(11, 4)
<class 'pandas.core.frame.DataFrame'>
(11, 5)
<class 'pandas.core.frame.DataFrame'>
(11, 21)
<class 'pandas.core.frame.DataFrame'>
(11, 30)
<class 'pandas.core.frame.DataFrame'>
(11, 32)
<class 'pandas.core.frame.DataFrame'>
(11, 37)
<class 'pandas.core.frame.DataFrame'>
(12, 7)
<class 'pandas.core.frame.DataFrame'>
(12, 11)
<class 'pandas.core.frame.DataFrame'>
(12, 15)
<class 'pandas.core.frame.DataFrame'>
(12, 17)
<class 'pandas.core.frame.DataFrame'>
(12, 18)
<class 'pandas.core.frame.DataFrame'>
(12, 25)
<class 'pandas.core.frame.DataFrame'>
(12, 28)
<class 'pandas.core.frame.DataFrame'>
(12, 39)
<class 'pandas.core.frame.DataFrame'>
(13, 35)
<class 'pandas.core.frame.DataFrame'>

In [45]:
dsf = pd.read_csv("1_if1.csv",index_col=0)
dsf[dsf['item_id']==10991]

,date,item_id,cate_id,cate_level_id,brand_id,supplier_id,pv_ipv,pv_uv,cart_ipv,cart_uv,...,ss_pv_ipv,jhs_pv_ipv,ztc_pv_uv,tbk_pv_uv,ss_pv_uv,jhs_pv_uv,num_alipay_njhs,amt_alipay_njhs,qty_alipay_njhs,unum_alipay_njhs
203793,20151114,10991,13,1,198,1104,97,49,2,2,...,12,0,4,1,9,0,0,0.00,0,0
203794,20151211,10991,13,1,198,1104,84,40,2,2,...,17,0,0,0,13,0,0,0.00,0,0
203795,20151221,10991,13,1,198,1104,63,30,1,1,...,10,0,0,1,8,0,0,0.00,0,0
203796,20151010,10991,13,1,198,1104,25,10,2,2,...,3,0,0,0,2,0,0,0.00,0,0
203797,20151030,10991,13,1,198,1104,70,53,2,2,...,24,0,0,0,20,0,0,0.00,0,0
203798,20151002,10991,13,1,198,1104,85,40,1,1,...,8,0,0,2,6,0,0,0.00,0,0
203799,20151021,10991,13,1,198,1104,65,47,3,3,...,13,0,0,0,12,0,0,0.00,0,0
203800,20151220,10991,13,1,198,1104,127,63,0,0,...,20,0,0,2,14,0,0,0.00,0,0
203801,20150918,10991,13,1,198,1104,0,0,2,1,...,0,0,0,0,0,0,0,0.00,0,0
203802,20150913,10991,13,1,198,1104,9,5,0,0,...,1,0,0,0,1,0,0,0.00,0,0
203803,20150917,10991,13,1,198,1104,13,9,0,0,...,5,0,0,0,4,0,0,0.00,0,0
203804,20151206,10991,13,1,198,1104,130,56,2,2,...,23,0,0,0,13,0,0,0.00,0,0
203805,20151104,10991,13,1,198,1104,351,174,12,11,...,50,0,5,1,40,0,0,0.00,0,0
203806,20151217,10991,13,1,198,1104,71,47,1,1,...,19,0,1,0,16,0,0,0.00,0,0
203807,20151023,10991,13,1,198,1104,102,49,6,6,...,17,0,0,1,13,0,0,0.00,0,0
203808,20150921,10991,13,1,198,1104,25,8,1,1,...,1,0,0,0,1,0,0,0.00,0,0
203809,20151203,10991,13,1,198,1104,78,40,2,2,...,20,0,0,0,9,0,0,0.00,0,0
203810,20150914,10991,13,1,198,1104,22,9,1,1,...,4,0,0,0,2,0,0,0.00,0,0
203811,20151110,10991,13,1,198,1104,1154,598,18,15,...,272,0,6,4,213,0,0,0.00,0,0
203812,20151208,10991,13,1,198,1104,110,59,3,2,...,25,0,1,0,17,0,0,0.00,0,0
203813,20151218,10991,13,1,198,1104,72,38,1,1,...,21,0,1,0,12,0,0,0.00,0,0
203814,20151123,10991,13,1,198,1104,91,44,1,1,...,16,0,1,0,10,0,0,0.00,0,0
203815,20151214,10991,13,1,198,1104,8,4,2,2,...,1,0,1,0,1,0,0,0.00,0,0
203816,20150925,10991,13,1,198,1104,16,11,1,1,...,0,0,0,0,0,0,0,0.00,0,0
203817,20151207,10991,13,1,198,1104,63,27,0,0,...,22,0,0,0,11,0,0,0.00,0,0
203818,20151027,10991,13,1,198,1104,173,91,1,1,...,42,0,1,2,27,0,0,0.00,0,0
203819,20150923,10991,13,1,198,1104,4,3,0,0,...,0,0,0,0,0,0,0,0.00,0,0
203820,20151013,10991,13,1,198,1104,40,25,0,0,...,23,0,0,0,14,0,0,0.00,0,0
203821,20151227,10991,13,1,198,1104,46,30,1,1,...,12,0,0,0,10,0,0,0.00,0,0
203822,20150929,10991,13,1,198,1104,44,23,3,2,...,14,0,0,0,6,0,1,7034.62,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
203871,20151001,10991,13,1,198,1104,148,76,1,1,...,38,0,0,0,20,0,0,0.00,0,0
203872,20151012,10991,13,1,198,1104,109,48,1,1,...,25,0,0,1,16,0,0,0.00,0,0
203873,20150930,10991,13,1,198,1104,47,30,6,4,...,24,0,0,0,16,0,0,0.00,0,0
203874,20151107,10991,13,1,198,1104,405,235,12,11,...,100,0,4,2,73,0,0,0.00,0,0
203875,20151215,10991,13,1,198,1104,107,56,1,1,...,19,0,2,0,13,0,0,0.00,0,0
203876,20151022,10991,13,1,198,1104,87,47,4,3,...,24,0,0,0,12,0,0,0.00,0,0
203877,20151118,10991,13,1,198,1104,36,13,0,0,...,4,0,0,0,3,0,0,0.00,0,0
203878,20151120,10991,13,1,198,1104,18,8,1,1,...,1,0,0,0,1,0,0,0.00,0,0
203879,20151015,10991,13,1,198,1104,43,24,1,1,...,19,0,0,0,10,0,0,0.00,0,0
203880,20151209,10991,13,1,198,1104,63,26,2,2,...,17,0,0,0,9,0,0,0.00,0,0
203881,20151026,10991,13,1,198,1104,127,65,2,1,...,24,0,1,0,15,0,0,0.00,0,0
203882,20151109,10991,13,1,198,1104,545,277,17,14,...,129,0,3,1,96,0,0,0.00,0,0
203883,20150922,10991,13,1,198,1104,3,2,1,1,...,1,0,0,0,1,0,0,0.00,0,0
203884,20150911,10991,13,1,198,1104,4,2,0,0,...,2,0,0,0,1,0,0,0.00,0,0
203885,20151122,10991,13,1,198,1104,36,23,0,0,...,11,0,1,1,5,0,0,0.00,0,0
203886,20151017,10991,13,1,198,1104,168,84,8,5,...,18,0,0,0,16,0,0,0.00,0,0
203887,20151126,10991,13,1,198,1104,13,7,0,0,...,5,0,1,0,4,0,0,0.00,0,0
203888,20151223,10991,13,1,198,1104,47,25,1,1,...,11,0,1,0,10,0,0,0.00,0,0
203889,20151226,10991,13,1,198,1104,37,18,2,2,...,1,0,1,0,1,0,0,0.00,0,0
203890,20151031,10991,13,1,198,1104,226,107,7,5,...,84,0,3,0,42,0,1,7431.50,1,1
203891,20151216,10991,13,1,198,1104,44,25,1,1,...,13,0,1,0,11,0,0,0.00,0,0
203892,20151003,10991,13,1,198,1104,101,64,5,5,...,24,0,0,0,19,0,0,0.00,0,0
203893,20151009,10991,13,1,198,1104,18,16,0,0,...,5,0,0,1,4,0,1,7431.50,1,1
203894,20151005,10991,13,1,198,1104,82,49,1,1,...,13,0,0,0,11,0,0,0.00,0,0
203895,20151121,10991,13,1,198,1104,66,43,1,1,...,22,0,0,1,12,0,0,0.00,0,0
203896,20151225,10991,13,1,198,1104,52,25,0,0,...,4,0,2,0,4,0,0,0.00,0,0
203897,20151101,10991,13,1,198,1104,306,166,11,6,...,83,0,1,0,60,0,0,0.00,0,0
203898,20151201,10991,13,1,198,1104,72,40,1,1,...,11,0,1,0,8,0,0,0.00,0,0
203899,20150919,10991,13,1,198,1104,14,9,1,1,...,5,0,0,0,4,0,0,0.00,0,0
203900,20151029,10991,13,1,198,1104,154,91,5,4,...,49,0,1,0,38,0,0,0.00,0,0